version: "3.7"
services:
  discovery:
    image: ekharismanto/okta_project_school_ui:discovery 
    ports:
      - 8761:8761
  config:
    image: ekharismanto/okta_project_school_ui:config 
    volumes:
      - "./config-data:/var/config-data"
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://discovery:8761/eureka
         -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - discovery
    ports:
      - 8888:8888
  school-service:
    image: ekharismanto/okta_project_school_ui:school_service 
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    restart: on-failure
    depends_on:
      - discovery
      - config
    ports:
      - 8081:8081
  school-ui:
    image: ekharismanto/okta_project_school_ui:school_ui
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.profiles.active=production
    restart: on-failure
    depends_on:
      - discovery
      - config
    ports:
      - 8080:8080
